### ISSUE TITLE
YAML explicit declaration for Rails Projects

### ISSUE THREAD

**Issue by nsoufr** [ResultadosDigitais/feature_flagger#3]
## PROBLEM

Everyone can use any rollout identifier without any verification, which raise two main problems:
1. Undocumented rollouts;
2. Coworkers have difficult to understand the purpose of some keys;
## SOLUTION

Usage of a YAML file to explicitly declare and create documentation for the rollout key, like so:

``` yaml
account:
  email_marketing:
    whitelabel:
      description: Enables account to get access to the new Whitelabel feature;
```

To avoid developers to create undocumented rollouts, `rollout?` will raise an exception if the key is not declared in YAML config file.

Example:

``` ruby
  current_account.rollout?([:email_marketing, :whitelalbel])
  #=> Rollout::Errors::KeyNotFound
```
